require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'FoodStudyApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'FoodStudyAppTests' do
    inherit! :complete
    # Pods for testing
  end


  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  #pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency.podspec"
  #pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  #pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
  #pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  #pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  #pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
  #pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  #pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  #pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  #pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  #pod 'Permission-Motion', :path => "#{permissions_path}/Motion.podspec"
  #pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  #pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  #pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders.podspec"
  #pod 'Permission-Siri', :path => "#{permissions_path}/Siri.podspec"
  #pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition.podspec"
  #pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit.podspec"


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  post_install do |installer|
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
    #flipper_post_install(installer)
  end
end

target 'FoodStudyApp-tvOS' do
  # Pods for FoodStudyApp-tvOS

  target 'FoodStudyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
